In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [14]:
import pandas as pd

raw_df = pd.read_csv(
    "spam.csv",
    encoding="cp1252",
    engine="python"
)

In [15]:
raw_df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [16]:
df = raw_df[['v1', 'v2']].copy()
df.columns = ['label', 'sms_message']

In [17]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [18]:
df.label.unique()

array(['ham', 'spam'], dtype=object)

In [21]:
#df.sms_message.unique()

In [20]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

In [22]:
df.head()

   label                                        sms_message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [23]:
df["label"]=df.label.map({"ham":0,"spam":1})

In [26]:
import pandas as pd

df = pd.read_csv(
    "spam.csv",
    encoding="cp1252",
    sep=",",
    engine="python"
)

In [27]:
df = df[['v1', 'v2']]
df.columns = ['label', 'sms_message']

In [28]:
df.label.unique()

array(['ham', 'spam'], dtype=object)

In [29]:
df.sms_message.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: sms_message, dtype: object

In [31]:

df["label"] = df.label.map({"ham": 0, "spam": 1})

In [32]:
df["label"].value_counts()

label
0    4825
1     747
Name: count, dtype: int64

In [44]:
df.head()

   label                                        sms_message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [47]:
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    df['sms_message'],
    df['label'],
    test_size=0.2,
    random_state=42
)

In [48]:
len(X_train_text), len(X_test_text)

(4457, 1115)

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

count_vector = CountVectorizer()

In [51]:
type(count_vector)

sklearn.feature_extraction.text.CountVectorizer

In [52]:
count_vector

CountVectorizer()

In [53]:
X_train = count_vector.fit_transform(X_train_text)

In [54]:
X_train.shape

(4457, 7735)

In [55]:
X_test = count_vector.transform(X_test_text)

In [56]:
X_test.shape

(1115, 7735)

In [64]:
count_vector.get_feature_names_out()

array(['00', '000', '000pes', ..., 'ûïharry', 'ûò', 'ûówell'],
      shape=(7735,), dtype=object)

In [65]:
from sklearn.naive_bayes import MultinomialNB

In [66]:
naive_bayes=MultinomialNB

In [69]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

MultinomialNB()

In [71]:
type(nb_model)

sklearn.naive_bayes.MultinomialNB

In [73]:
predictions = nb_model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.9838565022421525

In [75]:
predictions

array([0, 0, 1, ..., 0, 0, 1], shape=(1115,))

In [78]:
predlist=list(zip(predictions,y_test))

In [80]:
#predlist

In [81]:
#Evaluating the model

In [82]:
from sklearn.metrics import accuracy_score,precision_score

In [83]:
score=accuracy_score(y_test,predictions)

In [84]:
score

0.9838565022421525

In [98]:
X_test_text.iloc[1089]

'Win the newest åÒHarry Potter and the Order of the Phoenix (Book 5) reply HARRY, answer 5 questions - chance to be the first among readers!'

In [95]:
msg_vector = count_vector.transform([X_test_text.iloc[1087]])
nb_model.predict(msg_vector)

array([0])

In [96]:
nb_model.predict(count_vector.transform([X_test_text.iloc[1087]]))

array([0])

In [105]:
sms1=input("Enter the SMS message received")
predict_sms = nb_model.predict(count_vector.transform([sms1]))
print(predict_sms[0])
if(predict_sms[0]==0):
    print("Message is ham")
else:
    print("Message is spam")

Enter the SMS message received Hey! lets meet today.

0
Message is ham

In [106]:
sms1=input("Enter the SMS message received")
predict_sms = nb_model.predict(count_vector.transform([sms1]))
print(predict_sms[0])
if(predict_sms[0]==0):
    print("Message is ham")
else:
    print("Message is spam")

Enter the SMS message received You've received prize money. Click to claim!

1
Message is spam